@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Boundary(dbnode1, "DbServer1", "Deployment Node: s000_db001") {
    ContainerDb(master, "Master", "PostgresPro 14", "Мастернода кластера PostgresPro")
    Container(patroni1, "Patroni", "", "")
    Rel_L(patroni1, master, "health")
    Lay_L(patroni1, master)
}

Boundary(dbnode2, "DbServer2", "Deployment Node: s000_db002") {
    Container(patroni2, "Patroni", "", "")
    ContainerDb(sync, "Sync", "PostgresPro 14", "Синхронная реплика кластера PostgresPro")
    Rel_R(patroni2, sync, "health")
    Lay_R(patroni2, sync)
}

Boundary(dbnode3, "DbArbitration", "Deployment Node: s000_db003") {
    Container(patroni3, "Patroni", "", "")
}

Rel(master, sync, "replication", "5432")

BiRel_L(patroni3, patroni1, "")
BiRel_L(patroni1, patroni2, "")
BiRel(patroni2, patroni3, "")

@enduml